deployment/minibadge/conf.json.template, src/main/resources/sql/001-init-schema.sql, src/main/resources/sql/002-init-functions-utils.sql, src/main/resources/sql/003-init-setting-tables.sql, src/main/resources/sql/004-init-badge-tables.sql, src/main/resources/sql/005-init-views.sql
=> chore(db): init SQL database

src/main/resources/public/sass/global/containers/_badge-assign.scss
css ajustements
https://jira.support-ent.fr/browse/MBA-40
=> fix(BadgeType):MBA-40 fix css more spaces between elems

src/main/resources/public/ts/directives/selected-list/selected-list.html
now can delete an elem of the list
https://jira.support-ent.fr/browse/MBA-39
=> fix(Badge-types): MBA-39 fix list elem is deleted correctly

src/main/resources/i18n/fr.json, src/main/resources/public/template/main.html, src/main/resources/public/ts/controllers/minibadge.controller.ts
retrait d une option . Correction de l'option restante
https://jira.support-ent.fr/browse/MBA-42
=> fix(myBadges):MBA-42 correct label and correct button

src/main/resources/public/sass/global/_mixins.scss, src/main/resources/public/sass/global/components/_badge.scss, src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/sass/global/containers/_container.scss, src/main/resources/public/ts/directives/badge-list/badge-list.html, src/main/resources/public/ts/directives/card/footer/badge-detail/badge-detail-footer.html
CSS adjustements
https://jira.support-ent.fr/browse/MBA-41
=> fix(BadgeList):#MBA-41:fix css more and align items

src/main/java/fr/cgi/minibadge/Minibadge.java, src/main/java/fr/cgi/minibadge/core/constants/Database.java, src/main/java/fr/cgi/minibadge/core/constants/EventBusConst.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/core/constants/Request.java, src/main/java/fr/cgi/minibadge/helper/PromiseHelper.java, src/main/java/fr/cgi/minibadge/model/User.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/UserService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java, src/main/resources/sql/010-badges-add-display-name.sql
ajout d un table user pour récuperer le display name des users
https://jira.support-ent.fr/browse/MBA-44
=> feat(User) #MBA-44: add table user and link it to badge table

src/main/resources/public/template/main.html, src/main/resources/public/ts/controllers/minibadge.controller.ts, src/main/resources/public/ts/directives/badge-list/badge-list.directive.ts, src/main/resources/public/ts/directives/badge-list/badge-list.html
open refused badges if elems match search
https://jira.support-ent.fr/browse/MBA-43
=> fix(Badges)MBA-43:fix search query -> now open refused badges

src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/model/BadgeProtagonistSetting.java, src/main/java/fr/cgi/minibadge/model/BadgeProtagonistSettingRelation.java, src/main/java/fr/cgi/minibadge/model/BadgeSetting.java, src/main/java/fr/cgi/minibadge/model/BadgeType.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/components/_icon.scss, src/main/resources/public/sass/global/components/_type.scss, src/main/resources/public/ts/directives/id-type/id-type.html, src/main/resources/public/ts/models/badge-protagonist-setting.model.ts, src/main/resources/public/ts/models/badge-settings.model.ts, src/main/resources/public/ts/models/badge-type.model.ts, src/main/resources/public/ts/models/model.ts
display target and assignor type on badges
https://jira.support-ent.fr/browse/MBA-38
=> feat(BadgeType) #MBA-38: display target and assignor type

src/main/resources/public/ts/directives/chart/chart.html
fix(chart) : #MBA-60 disable valid button when isMinibadgeAccepted check and isChartAccepted unchecked
[https://jira.support-ent.fr/browse/MBA-60](url)
=> fix(chart) : #MBA-60 disable valid button when isMinibadgeAccepted check and isChartAccepted unchecked

src/main/java/fr/cgi/minibadge/controller/BadgeController.java, src/main/java/fr/cgi/minibadge/controller/BadgeTypeController.java, src/main/java/fr/cgi/minibadge/controller/UserController.java, src/main/java/fr/cgi/minibadge/core/constants/Database.java, src/main/java/fr/cgi/minibadge/core/constants/EventBusConst.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/core/constants/Request.java, src/main/java/fr/cgi/minibadge/helper/Neo4jHelper.java, src/main/java/fr/cgi/minibadge/helper/RequestHelper.java, src/main/java/fr/cgi/minibadge/helper/SqlHelper.java, src/main/java/fr/cgi/minibadge/helper/UserHelper.java, src/main/java/fr/cgi/minibadge/model/User.java, src/main/java/fr/cgi/minibadge/service/BadgeAssignedService.java, src/main/java/fr/cgi/minibadge/service/BadgeService.java, src/main/java/fr/cgi/minibadge/service/BadgeTypeService.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/UserService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeAssignedService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeService.java, src/main/resources/sql/012-assigned-views-created-field.sql
Pour la page de détail d'un type de badge, préparation de 2 endpoints permettant de visualiser les utilisateurs m'ayant octroyé le badge actuel, et ceux l'ayant reçus.
https://confluence.support-ent.fr/display/BAD/Types
Les tests seront ajoutés dans la PR pour le frontEnd
[Jira - MBA-24](https://jira.support-ent.fr/browse/MBA-24)
=> feat(badge-type): #MBA-24 show list of concerned by badge type users backEnd part

src/main/resources/public/ts/controllers/main.ts
fix(settings) : #MBA-49 await for getSettings to not display error
go to minibadge
[https://jira.support-ent.fr/browse/MBA-49](url)
=> fix(settings) : #MBA-49 await for getSettings to not display error

src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeService.java
now filter corretly
https://jira.support-ent.fr/browse/MBA-15
=> fix(Badge-Assigned) #MBA-15: filter badge when badge is revoked

src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/template/badge-types.html, src/main/resources/public/ts/controllers/badge-types.controller.ts, src/main/resources/public/ts/directives/card/card.directive.ts, src/main/resources/public/ts/directives/card/card.html
disable badge type if you didnt accept the chart
https://jira.support-ent.fr/browse/MBA-59
=> fix(Badge-Type) #MBA-59: now disable badge types when refused minibadge

src/main/resources/public/sass/global/containers/_badge-assign.scss, src/main/resources/public/template/behaviours/sniplet-badge-assign.html
html adjustements 
https://jira.support-ent.fr/browse/MBA-56
=> fix(Badge-Assign) #MBA-56: add space between search and selected

src/main/java/fr/cgi/minibadge/controller/BadgeAssignedController.java, src/main/java/fr/cgi/minibadge/controller/UserController.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/helper/SettingHelper.java, src/main/java/fr/cgi/minibadge/model/BadgeProtagonistSetting.java, src/main/java/fr/cgi/minibadge/model/BadgeProtagonistSettingRelation.java, src/main/java/fr/cgi/minibadge/model/BadgeSetting.java, src/main/java/fr/cgi/minibadge/model/Model.java, src/main/java/fr/cgi/minibadge/model/User.java, src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java, src/main/java/fr/cgi/minibadge/service/UserService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java, src/main/resources/public/ts/models/badge-protagonist-setting.model.ts, src/main/resources/public/ts/models/badge-type.model.ts
Ajout de la restriction par default: assignable par un étudiant pour un étudiant.
l'UX en front sera géré dans un ticket ultérieur. il s'agit ici de se contenter de bloquer la recherche d'utilisateurs quand JE ou ILS ne correspondent pas aux règles.
- En tant que personnel, sur la modal d'assignation d'un badge
- essayer de rechercher un utilisateur (étudiant) sur lequel vous avec les droits de communication, et qui a accepté la chart.
- vous ne retrouvez pas cet utilisateur. (d'ailleurs en tant que personnel, vous n'en trouvez aucun).
- essayez en tant qu'étudiant
- ça fonctionne !
[Jira - MBA-33](https://jira.support-ent.fr/browse/MBA-33)
=> feat(badge-setting): #MBA-33 set badge default setting as assignor: student and receiver: student

src/main/java/fr/cgi/minibadge/controller/SettingController.java, src/main/java/fr/cgi/minibadge/core/constants/DateConst.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/helper/DateHelper.java, src/main/java/fr/cgi/minibadge/helper/SettingHelper.java, src/main/java/fr/cgi/minibadge/helper/SqlHelper.java, src/main/java/fr/cgi/minibadge/model/BadgeType.java, src/main/java/fr/cgi/minibadge/model/GlobalSettings.java, src/main/java/fr/cgi/minibadge/model/ThresholdSetting.java, src/main/java/fr/cgi/minibadge/model/TypeSetting.java, src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java, src/main/java/fr/cgi/minibadge/service/SettingService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeTypeService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultSettingService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/containers/_badge-assign.scss, src/main/resources/public/template/behaviours/sniplet-badge-assign.html, src/main/resources/public/ts/models/badge-type.model.ts, src/main/resources/public/ts/models/setting.model.ts, src/main/resources/public/ts/models/threshold-setting.model.ts, src/main/resources/public/ts/models/type-settings.model.ts, src/main/resources/public/ts/sniplets/badge-assign.sniplet.ts
Ajout de la restriction par default: 3 badges assignables par jours maximum.
- En tant qu'étudiant, sur la modal d'assignation d'un badge
- Ajouter 3 utilisateurs
- Un message d'erreur s'affiche en mentionnant que le nombre maximum d'assignation est atteint
- Ajouter un autre utilisateur
- le bouton de validation ne deviens plus cliquable !
- vérifier que l'assignation fonctionne marlgré tout, après plusieurs assignations différentes.
[Jira - MBA-31](https://jira.support-ent.fr/browse/MBA-31)
=> feat(badge-setting): #MBA-31 set user default setting as 3 badge assign a day

src/main/resources/public/sass/global/components/_given-array.scss, src/main/resources/public/sass/global/components/_periode-picker.scss, src/main/resources/public/sass/global/containers/_badge-given.scss
Fix css mobile on badge assigned
https://jira.support-ent.fr/browse/MBA-68
=> fix(BadgeAssigned)#MBA-68: fix mobile css

src/main/resources/public/template/main.html, src/main/resources/public/ts/controllers/minibadge.controller.ts, src/main/resources/public/ts/directives/chart/chart.directive.ts
Réinitialisation des valeurs de la charte en fonction des valeurs sauvegardées en préférence, à la fermeture de la lightbox correspondante.
- Avec un utilisateur, aller sur la modal concernant la charte
- désactiver le/les boutons
- fermer la modal (sans valider)
- en rouvrant la modal, on remarque que les valeurs ont étaient reset
-  désactiver le/les boutons
- valider la charte
- en rouvrant la modal, on voit que les modifications ont étaient pris en compte.
[Jira - MBA-62](https://jira.support-ent.fr/browse/MBA-62)
=> fix(badge-assign): #MBA-62 Reset Chart values when closing corresponding lightbox

src/main/resources/public/sass/global/_mixins.scss, src/main/resources/public/sass/global/components/_type.scss, src/main/resources/public/sass/global/components/_user-list.scss
Faire en sorte que les éléments de la liste des utilisateurs restent lisibles, et ce, de manière responsive.
- Aller sur la page d'un type de badge qui a beaucoup d'activité (badge reçus / badge assignés à d'autre users).
- Tester le responsive
- Constater que le nom des utilisateur reste lisible.
[Jira - MBA-69](https://jira.support-ent.fr/browse/MBA-69)
=> fix(badge-type): #MBA-69 make user-lists more responsive.

src/main/resources/public/sass/global/components/_given-array.scss
Ajout d'un hover sur l'icone de révocation d'un assignement.
- Aller sur page des badges décernés
- Passer la souris sur un icone de révocation
- Observer le hover !
[Jira - MBA-70](https://jira.support-ent.fr/browse/MBA-70)
=> fix(badge-given): #MBA-70 add hover on revoke assignment.

src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/ts/directives/badge-list/badge-list.html
- La carte du badge devient désormais cliquable, redirigant vers son type.
- Grossiment des 3 points (menu)
- Aller sur l'accueil du module
- Constater les changements.
[Jira - MBA-74](https://jira.support-ent.fr/browse/MBA-74)
=> fix(badge): #MBA-74 improve card type UX

src/main/resources/public/sass/global/_minibadge.scss, src/main/resources/public/sass/global/components/_type.scss, src/main/resources/public/sass/global/components/_user-list.scss, src/main/resources/public/ts/directives/card/card.html, src/main/resources/public/ts/directives/description-type/description-type.html, src/main/resources/public/ts/directives/user-list/user-list.html
Suppression de l'effet bold sur les différents titres, afin de correspondre aux maquettes.
- Aller sur la page de détail d'un type de badge
- Constater les changements
[Jira - MBA-73](https://jira.support-ent.fr/browse/MBA-73)
=> fix(badge): #MBA-73 remove bold on different titles

src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/sass/global/components/_icon.scss, src/main/resources/public/template/badge-types.html
Sur la liste des types de badge:
- Ajout d'un hover sur le bouton du footer, permettant de décerner un badge.
- Ajoute de l'icon info en haut à droite
- Aller sur la page de la collection de badge
- Observer les changements
[Jira - MBA-76](https://jira.support-ent.fr/browse/MBA-76)
=> feat(badge-card): #MBA-76 update UX, with hover on assigning button and new icons and new icon

src/main/java/fr/cgi/minibadge/core/constants/Database.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/helper/Neo4jHelper.java, src/main/java/fr/cgi/minibadge/model/BadgeAssignedStructure.java, src/main/java/fr/cgi/minibadge/model/Chart.java, src/main/java/fr/cgi/minibadge/model/User.java, src/main/java/fr/cgi/minibadge/security/UsersAssignRight.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeAssignedService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java, src/main/resources/sql/013-badge-assignement-strutures.sql
Ajout d'une table badge_assigned_structure permettant de lier les différentes structures liées à une assignation (l'assignant et le recevant). ajout du script permettant la sauvegarde dans cette table à chaque assignation.
- Décerner un des badges à plusieurs utilisateurs
- Vérifier en base si les données badge_assigned_structure correspondants se sont bien créées.
[Jira - MBA-79](https://jira.support-ent.fr/browse/MBA-79)
=> feat(chart): #MBA-79 link assignments to structures concerned

src/main/resources/sql/003-init-setting-tables.sql
Enable deploy all SQL scripts
Drop minibdage schema and check if all scripts passed
[https://jira.support-ent.fr/browse/MBA-28](url)
=> fix(sql) : #MBA-28 fix deploy scripts

src/main/java/fr/cgi/minibadge/service/UserService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java
A partir d'un utilisateur, récupére les structures et les sous-structures auxquelles il est rattaché
A tester avec la MBA-84 (dans un premier temps, puis les autres tickets concernant les métriques de statistics.)
[Jira - MBA-92](https://jira.support-ent.fr/browse/MBA-92)
=> feat(statistics): #MBA-92 create service to get structure with substructure ids.

jest.config.js, src/main/resources/public/ts/services/__test__/minibadge.service.test.ts
Add default test for node
Only build-node-test pipe line must pass
#47
=> chore(test): #47 add default test for node

src/main/java/fr/cgi/minibadge/Minibadge.java, src/main/java/fr/cgi/minibadge/controller/StatisticController.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/helper/SqlHelper.java, src/main/java/fr/cgi/minibadge/model/Statistics.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/StatisticService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultStatisticService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultUserService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/statistics.html, src/main/resources/public/ts/controllers/statistics.controller.ts, src/main/resources/public/ts/models/statistic.model.ts, src/main/resources/public/ts/services/index.ts, src/main/resources/public/ts/services/statistic.service.ts
Ajout de la métrique comptant le nombre total d'assignation.
- Aller sur la page des statistiques
- Observer le nombre badges décernés se modifier.
[Jira - MBA-84](https://jira.support-ent.fr/browse/MBA-84)
=> feat(statistics-metrics): #MBA-84 get number badge assigned

src/main/java/fr/cgi/minibadge/Minibadge.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/model/BadgeType.java, src/main/java/fr/cgi/minibadge/model/Config.java, src/main/java/fr/cgi/minibadge/model/Statistics.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultStatisticService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/sass/global/components/_type.scss, src/main/resources/public/sass/global/containers/_statistics.scss, src/main/resources/public/template/statistics.html, src/main/resources/public/ts/directives/card/card-type-stat.directive.ts, src/main/resources/public/ts/directives/card/card-type-stat.html, src/main/resources/public/ts/directives/container/container.html, src/main/resources/public/ts/directives/index.ts, src/main/resources/public/ts/models/badge-type.model.ts, src/main/resources/public/ts/models/statistic.model.ts
Ajout de la métrique récupérant la liste des types de badges les plus assignés.
- Aller sur la page des statistiques
- Observer la partie "badges les plus décernés".
[Jira - MBA-85](https://jira.support-ent.fr/browse/MBA-85)
=> feat(statistics-metrics): #MBA-85 get list most assigned badges

src/main/java/fr/cgi/minibadge/core/constants/Database.java, src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/model/BadgeType.java, src/main/java/fr/cgi/minibadge/model/Config.java, src/main/java/fr/cgi/minibadge/model/Statistics.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultBadgeService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultStatisticService.java, src/main/resources/public/sass/global/components/_card.scss, src/main/resources/public/sass/global/components/_container.scss, src/main/resources/public/sass/global/containers/_statistics.scss, src/main/resources/public/template/statistics.html, src/main/resources/public/ts/controllers/statistics.controller.ts, src/main/resources/public/ts/directives/card/card-type-stat.directive.ts, src/main/resources/public/ts/directives/card/card-type-stat.html, src/main/resources/public/ts/models/statistic.model.ts, src/main/resources/public/ts/utils/number.utils.ts
Ajout de la métrique permettant de récupérer la liste des badges les plus refusés
- Aller sur la page des statistiques
- Observer la partie "badges les plus décernés".
[Jira - MBA-87](https://jira.support-ent.fr/browse/MBA-87)
=> feat(statistics-metrics): #MBA-87 get list most refused badges

gradle.properties, gulpfile.js, package.json, src/main/resources/view-src/minibadge.html
prepare 4.6.0 migration
compile and check with new springboard
=> chore: prepare 4.6.0 migration

src/main/java/fr/cgi/minibadge/core/constants/Field.java, src/main/java/fr/cgi/minibadge/model/Config.java, src/main/java/fr/cgi/minibadge/model/Statistics.java, src/main/java/fr/cgi/minibadge/model/Structure.java, src/main/java/fr/cgi/minibadge/model/User.java, src/main/java/fr/cgi/minibadge/service/ServiceFactory.java, src/main/java/fr/cgi/minibadge/service/StructureService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultStatisticService.java, src/main/java/fr/cgi/minibadge/service/impl/DefaultStructureService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/containers/_statistics.scss, src/main/resources/public/template/statistics.html, src/main/resources/public/ts/controllers/statistics.controller.ts, src/main/resources/public/ts/directives/list/list.directive.ts, src/main/resources/public/ts/directives/list/list.html, src/main/resources/public/ts/models/statistic.model.ts, src/main/resources/public/ts/models/structure.model.ts
Ajout de la métrique permettant de récupérer la liste des structures les plus assignantes.
- Aller sur la page des statistiques
- Observer la partie "Les établissements les plus actifs"
[Jira - MBA-90](https://jira.support-ent.fr/browse/MBA-90)
=> feat(statistics-metrics): #MBA-90 get list most assigning structures

gulpfile.js, package.json, src/main/resources/public/ts/directives/badge-given-array/badge-given-array.ts, src/main/resources/public/ts/models/__mocks__/entcore.ts, src/main/resources/public/ts/models/badge-assigned.model.ts, src/main/resources/public/ts/services/chart.service.ts
Ajout de la lib material design icons. Fix l'erreur de compilation du à la 4.6
- aller sur minibadge
- observer que les icones sont toujours en place.
[Jira - MBA-36](https://jira.support-ent.fr/browse/MBA-36)
=> fix(icons): #MBA-36 fix icons and compilation errors
